# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0102e3af6ea58c9289e284057f93fb0a42654c27b127ed8d52fb76b69ff2de73bd33999ac747946b990836bdc138ea7c6953a8de4188a75ca03bb09ef9f89e0

test:
  secret_key_base: dd22c4e1c21cbfee211262af8c8bf17827a708c5b829083520f8ff29eebc694aefec68a4e3ec03fa67cee7b8a0c3a1bdace50e7c59fc6ef267748f2b01491155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
